"""create_user_and_review_tables

Revision ID: 9b86a0b7ab37
Revises: f2c3466963b8
Create Date: 2025-06-02 15:07:02.999621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b86a0b7ab37'
down_revision = 'f2c3466963b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
