"""init

Revision ID: b514487c66c6
Revises: 6ddd6f77744e
Create Date: 2025-06-02 18:42:58.958959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b514487c66c6'
down_revision = '6ddd6f77744e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
